/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardChar123IdChar125RouteImport } from './routes/board.{-$id}'
import { Route as BoardsChar123IdChar125RouteImport } from './routes/boards.{-$id}'
import { Route as ErrorsChar123IdChar125RouteImport } from './routes/errors.{-$id}'
import { Route as PullRequestsChar123IdChar125RouteImport } from './routes/pull-requests.{-$id}'

const AccountsChar123IdChar125LazyRouteImport =
  createFileRoute('/accounts/{-$id}')()
const ActivityChar123IdChar125LazyRouteImport =
  createFileRoute('/activity/{-$id}')()
const ArchiveChar123IdChar125LazyRouteImport =
  createFileRoute('/archive/{-$id}')()
const AskChar123IdChar125LazyRouteImport = createFileRoute('/ask/{-$id}')()
const CalendarChar123IdChar125LazyRouteImport =
  createFileRoute('/calendar/{-$id}')()
const FlowChar123IdChar125LazyRouteImport = createFileRoute('/flow/{-$id}')()
const InboxChar123IdChar125LazyRouteImport = createFileRoute('/inbox/{-$id}')()
const MeetingsChar123IdChar125LazyRouteImport =
  createFileRoute('/meetings/{-$id}')()
const PlaybooksChar123IdChar125LazyRouteImport =
  createFileRoute('/playbooks/{-$id}')()
const SessionsChar123IdChar125LazyRouteImport =
  createFileRoute('/sessions/{-$id}')()
const SettingsChar123IdChar125LazyRouteImport =
  createFileRoute('/settings/{-$id}')()
const SlackChar123IdChar125LazyRouteImport = createFileRoute('/slack/{-$id}')()
const TicketsChar123IdChar125LazyRouteImport =
  createFileRoute('/tickets/{-$id}')()
const TodayChar123IdChar125LazyRouteImport = createFileRoute('/today/{-$id}')()
const VaultChar123IdChar125LazyRouteImport = createFileRoute('/vault/{-$id}')()
const WorkspaceChar123IdChar125LazyRouteImport =
  createFileRoute('/workspace/{-$id}')()
const WorkspacesChar123IdChar125LazyRouteImport =
  createFileRoute('/workspaces/{-$id}')()

const AccountsChar123IdChar125LazyRoute =
  AccountsChar123IdChar125LazyRouteImport.update({
    id: '/accounts/{-$id}',
    path: '/accounts/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/accounts.{-$id}.lazy').then((d) => d.Route),
  )
const ActivityChar123IdChar125LazyRoute =
  ActivityChar123IdChar125LazyRouteImport.update({
    id: '/activity/{-$id}',
    path: '/activity/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/activity.{-$id}.lazy').then((d) => d.Route),
  )
const ArchiveChar123IdChar125LazyRoute =
  ArchiveChar123IdChar125LazyRouteImport.update({
    id: '/archive/{-$id}',
    path: '/archive/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/archive.{-$id}.lazy').then((d) => d.Route),
  )
const AskChar123IdChar125LazyRoute = AskChar123IdChar125LazyRouteImport.update({
  id: '/ask/{-$id}',
  path: '/ask/{-$id}',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ask.{-$id}.lazy').then((d) => d.Route))
const BoardChar123IdChar125Route = BoardChar123IdChar125RouteImport.update({
  id: '/board/{-$id}',
  path: '/board/{-$id}',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/board.{-$id}.lazy').then((d) => d.Route))
const BoardsChar123IdChar125Route = BoardsChar123IdChar125RouteImport.update({
  id: '/boards/{-$id}',
  path: '/boards/{-$id}',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/boards.{-$id}.lazy').then((d) => d.Route))
const CalendarChar123IdChar125LazyRoute =
  CalendarChar123IdChar125LazyRouteImport.update({
    id: '/calendar/{-$id}',
    path: '/calendar/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/calendar.{-$id}.lazy').then((d) => d.Route),
  )
const ErrorsChar123IdChar125Route = ErrorsChar123IdChar125RouteImport.update({
  id: '/errors/{-$id}',
  path: '/errors/{-$id}',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/errors.{-$id}.lazy').then((d) => d.Route))
const FlowChar123IdChar125LazyRoute =
  FlowChar123IdChar125LazyRouteImport.update({
    id: '/flow/{-$id}',
    path: '/flow/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() => import('./routes/flow.{-$id}.lazy').then((d) => d.Route))
const InboxChar123IdChar125LazyRoute =
  InboxChar123IdChar125LazyRouteImport.update({
    id: '/inbox/{-$id}',
    path: '/inbox/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inbox.{-$id}.lazy').then((d) => d.Route),
  )
const MeetingsChar123IdChar125LazyRoute =
  MeetingsChar123IdChar125LazyRouteImport.update({
    id: '/meetings/{-$id}',
    path: '/meetings/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/meetings.{-$id}.lazy').then((d) => d.Route),
  )
const PlaybooksChar123IdChar125LazyRoute =
  PlaybooksChar123IdChar125LazyRouteImport.update({
    id: '/playbooks/{-$id}',
    path: '/playbooks/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/playbooks.{-$id}.lazy').then((d) => d.Route),
  )
const PullRequestsChar123IdChar125Route =
  PullRequestsChar123IdChar125RouteImport.update({
    id: '/pull-requests/{-$id}',
    path: '/pull-requests/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/pull-requests.{-$id}.lazy').then((d) => d.Route),
  )
const SessionsChar123IdChar125LazyRoute =
  SessionsChar123IdChar125LazyRouteImport.update({
    id: '/sessions/{-$id}',
    path: '/sessions/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/sessions.{-$id}.lazy').then((d) => d.Route),
  )
const SettingsChar123IdChar125LazyRoute =
  SettingsChar123IdChar125LazyRouteImport.update({
    id: '/settings/{-$id}',
    path: '/settings/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings.{-$id}.lazy').then((d) => d.Route),
  )
const SlackChar123IdChar125LazyRoute =
  SlackChar123IdChar125LazyRouteImport.update({
    id: '/slack/{-$id}',
    path: '/slack/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/slack.{-$id}.lazy').then((d) => d.Route),
  )
const TicketsChar123IdChar125LazyRoute =
  TicketsChar123IdChar125LazyRouteImport.update({
    id: '/tickets/{-$id}',
    path: '/tickets/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/tickets.{-$id}.lazy').then((d) => d.Route),
  )
const TodayChar123IdChar125LazyRoute =
  TodayChar123IdChar125LazyRouteImport.update({
    id: '/today/{-$id}',
    path: '/today/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/today.{-$id}.lazy').then((d) => d.Route),
  )
const VaultChar123IdChar125LazyRoute =
  VaultChar123IdChar125LazyRouteImport.update({
    id: '/vault/{-$id}',
    path: '/vault/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/vault.{-$id}.lazy').then((d) => d.Route),
  )
const WorkspaceChar123IdChar125LazyRoute =
  WorkspaceChar123IdChar125LazyRouteImport.update({
    id: '/workspace/{-$id}',
    path: '/workspace/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/workspace.{-$id}.lazy').then((d) => d.Route),
  )
const WorkspacesChar123IdChar125LazyRoute =
  WorkspacesChar123IdChar125LazyRouteImport.update({
    id: '/workspaces/{-$id}',
    path: '/workspaces/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/workspaces.{-$id}.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/board/{-$id}': typeof BoardChar123IdChar125Route
  '/boards/{-$id}': typeof BoardsChar123IdChar125Route
  '/errors/{-$id}': typeof ErrorsChar123IdChar125Route
  '/pull-requests/{-$id}': typeof PullRequestsChar123IdChar125Route
  '/accounts/{-$id}': typeof AccountsChar123IdChar125LazyRoute
  '/activity/{-$id}': typeof ActivityChar123IdChar125LazyRoute
  '/archive/{-$id}': typeof ArchiveChar123IdChar125LazyRoute
  '/ask/{-$id}': typeof AskChar123IdChar125LazyRoute
  '/calendar/{-$id}': typeof CalendarChar123IdChar125LazyRoute
  '/flow/{-$id}': typeof FlowChar123IdChar125LazyRoute
  '/inbox/{-$id}': typeof InboxChar123IdChar125LazyRoute
  '/meetings/{-$id}': typeof MeetingsChar123IdChar125LazyRoute
  '/playbooks/{-$id}': typeof PlaybooksChar123IdChar125LazyRoute
  '/sessions/{-$id}': typeof SessionsChar123IdChar125LazyRoute
  '/settings/{-$id}': typeof SettingsChar123IdChar125LazyRoute
  '/slack/{-$id}': typeof SlackChar123IdChar125LazyRoute
  '/tickets/{-$id}': typeof TicketsChar123IdChar125LazyRoute
  '/today/{-$id}': typeof TodayChar123IdChar125LazyRoute
  '/vault/{-$id}': typeof VaultChar123IdChar125LazyRoute
  '/workspace/{-$id}': typeof WorkspaceChar123IdChar125LazyRoute
  '/workspaces/{-$id}': typeof WorkspacesChar123IdChar125LazyRoute
}
export interface FileRoutesByTo {
  '/board/{-$id}': typeof BoardChar123IdChar125Route
  '/boards/{-$id}': typeof BoardsChar123IdChar125Route
  '/errors/{-$id}': typeof ErrorsChar123IdChar125Route
  '/pull-requests/{-$id}': typeof PullRequestsChar123IdChar125Route
  '/accounts/{-$id}': typeof AccountsChar123IdChar125LazyRoute
  '/activity/{-$id}': typeof ActivityChar123IdChar125LazyRoute
  '/archive/{-$id}': typeof ArchiveChar123IdChar125LazyRoute
  '/ask/{-$id}': typeof AskChar123IdChar125LazyRoute
  '/calendar/{-$id}': typeof CalendarChar123IdChar125LazyRoute
  '/flow/{-$id}': typeof FlowChar123IdChar125LazyRoute
  '/inbox/{-$id}': typeof InboxChar123IdChar125LazyRoute
  '/meetings/{-$id}': typeof MeetingsChar123IdChar125LazyRoute
  '/playbooks/{-$id}': typeof PlaybooksChar123IdChar125LazyRoute
  '/sessions/{-$id}': typeof SessionsChar123IdChar125LazyRoute
  '/settings/{-$id}': typeof SettingsChar123IdChar125LazyRoute
  '/slack/{-$id}': typeof SlackChar123IdChar125LazyRoute
  '/tickets/{-$id}': typeof TicketsChar123IdChar125LazyRoute
  '/today/{-$id}': typeof TodayChar123IdChar125LazyRoute
  '/vault/{-$id}': typeof VaultChar123IdChar125LazyRoute
  '/workspace/{-$id}': typeof WorkspaceChar123IdChar125LazyRoute
  '/workspaces/{-$id}': typeof WorkspacesChar123IdChar125LazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/board/{-$id}': typeof BoardChar123IdChar125Route
  '/boards/{-$id}': typeof BoardsChar123IdChar125Route
  '/errors/{-$id}': typeof ErrorsChar123IdChar125Route
  '/pull-requests/{-$id}': typeof PullRequestsChar123IdChar125Route
  '/accounts/{-$id}': typeof AccountsChar123IdChar125LazyRoute
  '/activity/{-$id}': typeof ActivityChar123IdChar125LazyRoute
  '/archive/{-$id}': typeof ArchiveChar123IdChar125LazyRoute
  '/ask/{-$id}': typeof AskChar123IdChar125LazyRoute
  '/calendar/{-$id}': typeof CalendarChar123IdChar125LazyRoute
  '/flow/{-$id}': typeof FlowChar123IdChar125LazyRoute
  '/inbox/{-$id}': typeof InboxChar123IdChar125LazyRoute
  '/meetings/{-$id}': typeof MeetingsChar123IdChar125LazyRoute
  '/playbooks/{-$id}': typeof PlaybooksChar123IdChar125LazyRoute
  '/sessions/{-$id}': typeof SessionsChar123IdChar125LazyRoute
  '/settings/{-$id}': typeof SettingsChar123IdChar125LazyRoute
  '/slack/{-$id}': typeof SlackChar123IdChar125LazyRoute
  '/tickets/{-$id}': typeof TicketsChar123IdChar125LazyRoute
  '/today/{-$id}': typeof TodayChar123IdChar125LazyRoute
  '/vault/{-$id}': typeof VaultChar123IdChar125LazyRoute
  '/workspace/{-$id}': typeof WorkspaceChar123IdChar125LazyRoute
  '/workspaces/{-$id}': typeof WorkspacesChar123IdChar125LazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/board/{-$id}'
    | '/boards/{-$id}'
    | '/errors/{-$id}'
    | '/pull-requests/{-$id}'
    | '/accounts/{-$id}'
    | '/activity/{-$id}'
    | '/archive/{-$id}'
    | '/ask/{-$id}'
    | '/calendar/{-$id}'
    | '/flow/{-$id}'
    | '/inbox/{-$id}'
    | '/meetings/{-$id}'
    | '/playbooks/{-$id}'
    | '/sessions/{-$id}'
    | '/settings/{-$id}'
    | '/slack/{-$id}'
    | '/tickets/{-$id}'
    | '/today/{-$id}'
    | '/vault/{-$id}'
    | '/workspace/{-$id}'
    | '/workspaces/{-$id}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/board/{-$id}'
    | '/boards/{-$id}'
    | '/errors/{-$id}'
    | '/pull-requests/{-$id}'
    | '/accounts/{-$id}'
    | '/activity/{-$id}'
    | '/archive/{-$id}'
    | '/ask/{-$id}'
    | '/calendar/{-$id}'
    | '/flow/{-$id}'
    | '/inbox/{-$id}'
    | '/meetings/{-$id}'
    | '/playbooks/{-$id}'
    | '/sessions/{-$id}'
    | '/settings/{-$id}'
    | '/slack/{-$id}'
    | '/tickets/{-$id}'
    | '/today/{-$id}'
    | '/vault/{-$id}'
    | '/workspace/{-$id}'
    | '/workspaces/{-$id}'
  id:
    | '__root__'
    | '/board/{-$id}'
    | '/boards/{-$id}'
    | '/errors/{-$id}'
    | '/pull-requests/{-$id}'
    | '/accounts/{-$id}'
    | '/activity/{-$id}'
    | '/archive/{-$id}'
    | '/ask/{-$id}'
    | '/calendar/{-$id}'
    | '/flow/{-$id}'
    | '/inbox/{-$id}'
    | '/meetings/{-$id}'
    | '/playbooks/{-$id}'
    | '/sessions/{-$id}'
    | '/settings/{-$id}'
    | '/slack/{-$id}'
    | '/tickets/{-$id}'
    | '/today/{-$id}'
    | '/vault/{-$id}'
    | '/workspace/{-$id}'
    | '/workspaces/{-$id}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BoardChar123IdChar125Route: typeof BoardChar123IdChar125Route
  BoardsChar123IdChar125Route: typeof BoardsChar123IdChar125Route
  ErrorsChar123IdChar125Route: typeof ErrorsChar123IdChar125Route
  PullRequestsChar123IdChar125Route: typeof PullRequestsChar123IdChar125Route
  AccountsChar123IdChar125LazyRoute: typeof AccountsChar123IdChar125LazyRoute
  ActivityChar123IdChar125LazyRoute: typeof ActivityChar123IdChar125LazyRoute
  ArchiveChar123IdChar125LazyRoute: typeof ArchiveChar123IdChar125LazyRoute
  AskChar123IdChar125LazyRoute: typeof AskChar123IdChar125LazyRoute
  CalendarChar123IdChar125LazyRoute: typeof CalendarChar123IdChar125LazyRoute
  FlowChar123IdChar125LazyRoute: typeof FlowChar123IdChar125LazyRoute
  InboxChar123IdChar125LazyRoute: typeof InboxChar123IdChar125LazyRoute
  MeetingsChar123IdChar125LazyRoute: typeof MeetingsChar123IdChar125LazyRoute
  PlaybooksChar123IdChar125LazyRoute: typeof PlaybooksChar123IdChar125LazyRoute
  SessionsChar123IdChar125LazyRoute: typeof SessionsChar123IdChar125LazyRoute
  SettingsChar123IdChar125LazyRoute: typeof SettingsChar123IdChar125LazyRoute
  SlackChar123IdChar125LazyRoute: typeof SlackChar123IdChar125LazyRoute
  TicketsChar123IdChar125LazyRoute: typeof TicketsChar123IdChar125LazyRoute
  TodayChar123IdChar125LazyRoute: typeof TodayChar123IdChar125LazyRoute
  VaultChar123IdChar125LazyRoute: typeof VaultChar123IdChar125LazyRoute
  WorkspaceChar123IdChar125LazyRoute: typeof WorkspaceChar123IdChar125LazyRoute
  WorkspacesChar123IdChar125LazyRoute: typeof WorkspacesChar123IdChar125LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accounts/{-$id}': {
      id: '/accounts/{-$id}'
      path: '/accounts/{-$id}'
      fullPath: '/accounts/{-$id}'
      preLoaderRoute: typeof AccountsChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/{-$id}': {
      id: '/activity/{-$id}'
      path: '/activity/{-$id}'
      fullPath: '/activity/{-$id}'
      preLoaderRoute: typeof ActivityChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/{-$id}': {
      id: '/archive/{-$id}'
      path: '/archive/{-$id}'
      fullPath: '/archive/{-$id}'
      preLoaderRoute: typeof ArchiveChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/{-$id}': {
      id: '/ask/{-$id}'
      path: '/ask/{-$id}'
      fullPath: '/ask/{-$id}'
      preLoaderRoute: typeof AskChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/{-$id}': {
      id: '/board/{-$id}'
      path: '/board/{-$id}'
      fullPath: '/board/{-$id}'
      preLoaderRoute: typeof BoardChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/{-$id}': {
      id: '/boards/{-$id}'
      path: '/boards/{-$id}'
      fullPath: '/boards/{-$id}'
      preLoaderRoute: typeof BoardsChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/{-$id}': {
      id: '/calendar/{-$id}'
      path: '/calendar/{-$id}'
      fullPath: '/calendar/{-$id}'
      preLoaderRoute: typeof CalendarChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/{-$id}': {
      id: '/errors/{-$id}'
      path: '/errors/{-$id}'
      fullPath: '/errors/{-$id}'
      preLoaderRoute: typeof ErrorsChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/{-$id}': {
      id: '/flow/{-$id}'
      path: '/flow/{-$id}'
      fullPath: '/flow/{-$id}'
      preLoaderRoute: typeof FlowChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/{-$id}': {
      id: '/inbox/{-$id}'
      path: '/inbox/{-$id}'
      fullPath: '/inbox/{-$id}'
      preLoaderRoute: typeof InboxChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/{-$id}': {
      id: '/meetings/{-$id}'
      path: '/meetings/{-$id}'
      fullPath: '/meetings/{-$id}'
      preLoaderRoute: typeof MeetingsChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/{-$id}': {
      id: '/playbooks/{-$id}'
      path: '/playbooks/{-$id}'
      fullPath: '/playbooks/{-$id}'
      preLoaderRoute: typeof PlaybooksChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests/{-$id}': {
      id: '/pull-requests/{-$id}'
      path: '/pull-requests/{-$id}'
      fullPath: '/pull-requests/{-$id}'
      preLoaderRoute: typeof PullRequestsChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/{-$id}': {
      id: '/sessions/{-$id}'
      path: '/sessions/{-$id}'
      fullPath: '/sessions/{-$id}'
      preLoaderRoute: typeof SessionsChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/{-$id}': {
      id: '/settings/{-$id}'
      path: '/settings/{-$id}'
      fullPath: '/settings/{-$id}'
      preLoaderRoute: typeof SettingsChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack/{-$id}': {
      id: '/slack/{-$id}'
      path: '/slack/{-$id}'
      fullPath: '/slack/{-$id}'
      preLoaderRoute: typeof SlackChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/{-$id}': {
      id: '/tickets/{-$id}'
      path: '/tickets/{-$id}'
      fullPath: '/tickets/{-$id}'
      preLoaderRoute: typeof TicketsChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/{-$id}': {
      id: '/today/{-$id}'
      path: '/today/{-$id}'
      fullPath: '/today/{-$id}'
      preLoaderRoute: typeof TodayChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/{-$id}': {
      id: '/vault/{-$id}'
      path: '/vault/{-$id}'
      fullPath: '/vault/{-$id}'
      preLoaderRoute: typeof VaultChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/{-$id}': {
      id: '/workspace/{-$id}'
      path: '/workspace/{-$id}'
      fullPath: '/workspace/{-$id}'
      preLoaderRoute: typeof WorkspaceChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/{-$id}': {
      id: '/workspaces/{-$id}'
      path: '/workspaces/{-$id}'
      fullPath: '/workspaces/{-$id}'
      preLoaderRoute: typeof WorkspacesChar123IdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BoardChar123IdChar125Route: BoardChar123IdChar125Route,
  BoardsChar123IdChar125Route: BoardsChar123IdChar125Route,
  ErrorsChar123IdChar125Route: ErrorsChar123IdChar125Route,
  PullRequestsChar123IdChar125Route: PullRequestsChar123IdChar125Route,
  AccountsChar123IdChar125LazyRoute: AccountsChar123IdChar125LazyRoute,
  ActivityChar123IdChar125LazyRoute: ActivityChar123IdChar125LazyRoute,
  ArchiveChar123IdChar125LazyRoute: ArchiveChar123IdChar125LazyRoute,
  AskChar123IdChar125LazyRoute: AskChar123IdChar125LazyRoute,
  CalendarChar123IdChar125LazyRoute: CalendarChar123IdChar125LazyRoute,
  FlowChar123IdChar125LazyRoute: FlowChar123IdChar125LazyRoute,
  InboxChar123IdChar125LazyRoute: InboxChar123IdChar125LazyRoute,
  MeetingsChar123IdChar125LazyRoute: MeetingsChar123IdChar125LazyRoute,
  PlaybooksChar123IdChar125LazyRoute: PlaybooksChar123IdChar125LazyRoute,
  SessionsChar123IdChar125LazyRoute: SessionsChar123IdChar125LazyRoute,
  SettingsChar123IdChar125LazyRoute: SettingsChar123IdChar125LazyRoute,
  SlackChar123IdChar125LazyRoute: SlackChar123IdChar125LazyRoute,
  TicketsChar123IdChar125LazyRoute: TicketsChar123IdChar125LazyRoute,
  TodayChar123IdChar125LazyRoute: TodayChar123IdChar125LazyRoute,
  VaultChar123IdChar125LazyRoute: VaultChar123IdChar125LazyRoute,
  WorkspaceChar123IdChar125LazyRoute: WorkspaceChar123IdChar125LazyRoute,
  WorkspacesChar123IdChar125LazyRoute: WorkspacesChar123IdChar125LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
